---
- name: Debug and see shared location
  debug:
    msg: "{{ deploy_helper.shared_path }}"

- name: Check if redis-cache plugin is activated
  command: "wp plugin list | grep redis-cache | awk '{print $2}'"
  register: plugin_status

- name: Do these steps only if plugin is active
  block:

    - name: Enable redis-cache plugin
      command: "wp redis enable"
      args:
        chdir: "{{ deploy_helper.new_release_path }}"

    - name: Flush redis cache
      command: "wp cache flush"
      args:
        chdir: "{{ deploy_helper.new_release_path }}"

    - name: Flush redis DB
      shell: "redis-cli FLUSHALL"

  when: plugin_status.stdout is defined and plugin_status.stdout != "" and plugin_status.stdout != "inactive"
