---
- name: Debug and see shared location
  debug:
    msg: "{{ deploy_helper.shared_path }}"

- name: Enable redis-cache plugin
  command: "wp redis enable"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Flush redis cache
  command: "wp cache flush; redis-cli FLUSHALL"
